# Generated by Django 3.2.2 on 2021-06-25 06:34

import apps.products.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_measurement.models
import measurement.measures.distance
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(default='No aplica', max_length=50, verbose_name='Nombre')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('large_edge', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Canto largo')),
                ('short_edge', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Canto corto')),
                ('is_side', models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No'), (None, 'No aplica')], null=True, verbose_name='Es lateral?')),
            ],
            options={
                'verbose_name': 'composición del producto',
                'verbose_name_plural': 'composiciones de los productos',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('is_global', models.BooleanField(default=False, verbose_name='Es global')),
                ('user_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='compañía/usuario')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('attribute', models.CharField(choices=[('W', 'Ancho'), ('H', 'Alto'), ('L', 'Profundo')], max_length=50, verbose_name='Atributo')),
                ('operation', models.CharField(choices=[('SUM', 'Sumar'), ('SUB', 'Restar'), ('MUL', 'Multiplicar')], max_length=50, verbose_name='Operación')),
                ('value', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Valor')),
                ('composition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='products.composition', verbose_name='Composición')),
            ],
            options={
                'verbose_name': 'regla de despiece',
                'verbose_name_plural': 'reglas de los despieces',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('media', models.ImageField(upload_to=apps.products.models.custom_upload_product_media)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='products.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'fotos del producto',
                'verbose_name_plural': 'fotos de los productos',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('is_global', models.BooleanField(default=False, verbose_name='Es global')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('is_measurable', models.BooleanField(default=False, verbose_name='Es medible')),
                ('width', django_measurement.models.MeasurementField(blank=True, measurement=measurement.measures.distance.Distance, null=True, verbose_name='Ancho')),
                ('high', django_measurement.models.MeasurementField(blank=True, measurement=measurement.measures.distance.Distance, null=True, verbose_name='Alto')),
                ('photo', models.ImageField(blank=True, default='common/default_material.png', null=True, upload_to=apps.products.models.custom_upload_material_media, verbose_name='Foto')),
                ('user_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='compañía/usuario')),
            ],
            options={
                'verbose_name': 'material',
                'verbose_name_plural': 'materiales',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='composition',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compositions', to='products.material', verbose_name='Material'),
        ),
        migrations.AddField(
            model_name='composition',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compositions', to='products.product', verbose_name='Producto'),
        ),
    ]
