# Generated by Django 3.2 on 2021-05-08 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='compañía/usuario'),
        ),
        migrations.AddField(
            model_name='material',
            name='user_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='compañía/usuario'),
        ),
        migrations.AddField(
            model_name='composition',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.material', verbose_name='Material'),
        ),
        migrations.AddField(
            model_name='composition',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Producto'),
        ),
    ]
