# Generated by Django 3.2.2 on 2021-07-15 23:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_measurement.models
import measurement.measures.distance
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('width', django_measurement.models.MeasurementField(measurement=measurement.measures.distance.Distance, verbose_name='Ancho')),
                ('high', django_measurement.models.MeasurementField(measurement=measurement.measures.distance.Distance, verbose_name='Alto')),
                ('depth', django_measurement.models.MeasurementField(measurement=measurement.measures.distance.Distance, verbose_name='Profundidad')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio total')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'cotización',
                'verbose_name_plural': 'cotizaciones',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Quartering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('width', django_measurement.models.MeasurementField(blank=True, measurement=measurement.measures.distance.Distance, null=True, verbose_name='Ancho')),
                ('high', django_measurement.models.MeasurementField(blank=True, measurement=measurement.measures.distance.Distance, null=True, verbose_name='Alto')),
                ('depth', django_measurement.models.MeasurementField(blank=True, measurement=measurement.measures.distance.Distance, null=True, verbose_name='Profundidad')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio del material')),
                ('edge_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio del canto')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('composition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.composition', verbose_name='Elemento')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotations.quotation', verbose_name='Cotización')),
            ],
            options={
                'verbose_name': 'despiece',
                'verbose_name_plural': 'despieces',
                'ordering': ['-created'],
            },
        ),
    ]
